-- Version: 1.0.0.1
CREATE DATABASE IF NOT EXISTS ExampleDB;
USE ExampleDB;

CREATE TABLE IF NOT EXISTS VersionHistory (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    VersionNumber VARCHAR(20) NOT NULL,
    ActionType ENUM('UP', 'DOWN') NOT NULL,
    DateApplied DATETIME NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Products (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    Stock INT NOT NULL
) ENGINE=InnoDB;